services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable@sha256:3e2dff545c46e91f4ab2b21597016011d76d0de58bc8eaf51d75e841f337bf88"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/mnt/ceph/ha:/config"

    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.ha.rule=Host(`ha.apps.metalnet.org`) || Host(`ha`)
        - traefik.http.routers.ha.entrypoints=websecure
        - traefik.http.routers.ha.service=ha
        - traefik.http.routers.ha.tls=true
        - traefik.http.routers.ha.tls.certresolver=le
        - traefik.http.routers.ha.tls.domains[0].main=ha.apps.metalnet.org
        - traefik.http.services.ha.loadbalancer.server.port=8123
        - homepage.group=Applications
        - homepage.name=Home Assistant
        - homepage.href=https://ha.apps.metalnet.org/

    networks:
      - traefik

networks:
  traefik:
    external: true

